/*จงเขียนโปรแกรมเพื่อรับค่า n เข้าผ่านทางแป้นพิมพ์ จากนั้นให้เขียนฟังก์ชัน prime เพื่อแสดงจำนวนเฉพาะทุกค่าตั้งแต่ค่า 2 จนถึงจำนวนเต็มบวก n 

 * This source file was generated by the Gradle 'init' task
 */
package prime4;

import java.util.Scanner;

public class App {
    public static boolean isPrime(int n) {
        if (n <= 1) {
            return false;
        }
        for (int i = 2; i <= Math.sqrt(n); i++) {
            if (n % i == 0) {
                return false;
            }
        }
        return true;
    }

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        System.out.print("Enter input number: ");
        int n = sc.nextInt();
        System.out.println("Prime numbers is");
        for (int i = 2; i <= n; i++) {
            if (isPrime(i)) {
                System.out.print(i + " ");
            }
        }
        sc.close();
    }

    public Object getGreeting() {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'getGreeting'");
    }
}